In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pymc3 as pm

Variables we want in our model are declared within the context of the `Model` object.

In [3]:
with pm.Model() as model:
    param = pm.Exponential('param_exp', 1)
    data_gen = pm.Poisson('data_poisson', param)

We can continue to work within the context of the same model by using with with the name of the model object that we have already created.

In [4]:
with model:
    data_gen_update = data_gen + 1

The test_value is used only for the model, as the starting point for sampling if no other start is specified. It will not change as a result of sampling.

In [7]:
# Print a value currently assigned to the variable
param.tag.test_value

array(0.69314718)

In [18]:
# Generate a set of random values
param.random(size=10)

array([2.8760929 , 2.43696   , 0.96827784, 0.20509402, 0.14093668,
       1.76281448, 1.92656645, 0.09719959, 0.74336827, 0.49224135])

We can change the test value by using the `testval` parameter when defining the variable.

In [20]:
with pm.Model() as model:
    param = pm.Exponential('param', 1, testval=0.5)

In [21]:
param.tag.test_value

array(0.5)

In [26]:
with pm.Model() as model:
    param = pm.Exponential('param', 1, shape=(2, 2))

In [27]:
param.tag.test_value

array([[0.69314718, 0.69314718],
       [0.69314718, 0.69314718]])

PyMC3 stochastic variables have a keyword argument observed. The keyword observed has a very simple role: fix the variable's current value to be the given data, typically a `NumPy` array or `Pandas` DataFrame.

In [28]:
data = np.array([10, 5])
with model:
    fixed_var = pm.Poisson("fixed_var", 1, observed=data)

In [29]:
fixed_var.tag.test_value

array([10,  5])